[package]
name = "example-bevy"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
particular = { path = "../../particular" }
bevy = "0.11.2"
bevy_egui = "0.21"
crossbeam-channel = "0"
humantime = "2"
