[package]
name = "particular"
version = "0.1.2"
edition = "2021"
authors = ["Canleskis"]
description = "Particular is crate providing a simple way to simulate N-body gravitational interaction of particles in Rust."
license-file = "LICENSE"
repository = "https://github.com/Canleskis/particular"
documentation = "https://docs.rs/particular"
keywords = ["n-body", "gravity"]
categories = ["aerospace", "simulation"]
exclude = ["particular_5000_bodies.gif"]

[dependencies]
rayon = "1.5.3"
glam = "0.21.3"
particular_derive = { path = "particular_derive", version = "0.1.0" }