[package]
name = "particular"
version = "0.2.0"
edition = "2021"
authors = ["Canleskis"]
description = "A simple, parallel N-body simulation library written in Rust."
license = "MIT OR Apache-2.0"
repository = "https://github.com/Canleskis/particular"
documentation = "https://docs.rs/particular"
keywords = ["n-body", "gravity"]
categories = ["simulation"]
exclude = ["particular_5000_bodies.gif"]

[features]
default = ["glam"]
parallel = ["dep:rayon"]
nalgebra = ["dep:nalgebra"]
glam = ["dep:glam"]
cgmath = ["dep:cgmath"]

[dependencies]
particular_derive = { path = "particular_derive", version = "0.2.0" }
rayon = { version = "1", optional = true }
nalgebra = { version = "0", optional = true }
glam = { version = "0", optional = true }
cgmath = { version = "0", optional = true }