[package]
name = "particular"
version = "0.1.6"
edition = "2021"
authors = ["Canleskis"]
description = "A simple, parallel N-body simulation library written in Rust."
license = "MIT OR Apache-2.0"
repository = "https://github.com/Canleskis/particular"
documentation = "https://docs.rs/particular"
keywords = ["n-body", "gravity"]
categories = ["simulation"]
exclude = ["particular_5000_bodies.gif"]

[dependencies]
rayon = { version = "1.5.3", optional = true }
glam = "0.21.3"
particular_derive = { path = "particular_derive", version = "0.1.1" }

[features]
parallel = ["dep:rayon"]