[package]
name = "particular"
version = "0.3.0"
edition = "2021"
authors = ["Canleskis"]
description = "A simple, parallel N-body simulation library written in Rust."
license = "MIT OR Apache-2.0"
repository = "https://github.com/Canleskis/particular"
documentation = "https://docs.rs/particular"
keywords = ["n-body", "gravity"]
categories = ["simulation"]
exclude = ["particular_5000_bodies.gif"]

[features]
parallel = ["dep:rayon"]

[dependencies]
particular_derive = { path = "particular_derive", version = "0.3.0" }
rayon = { version = "1", optional = true }
glam = "0"

[dev-dependencies]
criterion = "0"
rand = "0"

[[bench]]
name = "benchmark"
harness = false