[package]
name = "particular_derive"
version = "0.6.0"
edition = "2021"
authors = ["Canleskis"]
description = "Derive macro for the particular crate."
license = "MIT OR Apache-2.0"

[dependencies]
syn = "2"
quote = "1"

[lib]
proc_macro = true