[package]
name = "particular_derive"
description = "Derive macro for the particular crate."
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
syn = "2"
quote = "1"

[lib]
proc_macro = true