[package]
name = "particular_derive"
version = "0.3.0"
edition = "2021"
authors = ["Canleskis"]
description = "Derive macro for the 'particular' crate."
license = "MIT OR Apache-2.0"

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"

[lib]
proc_macro = true