[package]
name = "simple"
publish = false
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
particular = { path = "../../particular", features = ["glam"]}
glam = "0.24.2"