name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: Swatinem/rust-cache@v2
            
            - name: Build
              run: cargo build --verbose --all-features
            - name: Test
              run: cargo test --verbose --features parallel
            - name: Clippy
              run: cargo clippy --verbose --all-features -- -D warnings
