name: Deploy website

on:
    push:
        branches: ["website"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3.0.0

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  target: wasm32-unknown-unknown

            - name: Setup wasm-bindgen
              uses: jetli/wasm-bindgen-action@v0.2.0
              with:
                  version: "0.2.87"

            - name: Build Examples
              run: |
                  for subfolder in examples/*; do
                      if [ -d $subfolder ]; then
                          ./examples/deploy_example.sh $subfolder website/content/demos
                      fi
                  done

            - name: Deploy
              uses: shalzz/zola-deploy-action@v0.17.2
              env:
                  BUILD_DIR: website
                  PAGES_BRANCH: gh-pages
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
