name: Deploy website

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3.0.0

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  target: wasm32-unknown-unknown

            - uses: Swatinem/rust-cache@v2

            - name: Setup wasm-bindgen
              uses: jetli/wasm-bindgen-action@v0.2.0
              with:
                  version: "0.2.89"

            - name: Deploy Benchmarks
              run: |
                  bash ./.github/scripts/deploy_benchmarks.sh website/content/benchmarks

            - name: Deploy Examples
              run: |
                  ./.github/scripts/deploy_showcase.sh

            - name: Deploy Site
              uses: shalzz/zola-deploy-action@v0.17.2
              env:
                  BUILD_DIR: website
                  PAGES_BRANCH: gh-pages
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
