name: CI

on:
  push:
    branches: ${{ github.ref }}
  pull_request:
    branches: ${{ github.ref }}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --all-features
    - name: Test
      run: cargo test --verbose --features parallel
    - name: Clippy
      run: cargo clippy --verbose --all-features -- -D warnings 
